# Generated by Django 4.0.5 on 2022-06-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('uploaded_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
