# Generated by Django 4.0.5 on 2022-06-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_options_alter_blog_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
    ]
