# Generated by Django 4.0.5 on 2022-06-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['id'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('T', 'Текстовый блог'), ('P', 'Фотоблог'), ('A', 'Артблог'), ('M', 'Музыкальный блог')], default="Haven't choosen", max_length=25),
        ),
    ]
