# Generated by Django 4.0.5 on 2022-07-06 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_remove_blog_photos_photo_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='blogs.blog'),
        ),
    ]
